from enum import Enum, auto
from game.util.constants import *
class VicinityID(object):
    def __init__(self, character, id, supertype, transparent, walkable):
        self.character = character
        self.id = id
        self.supertype = supertype
        self.transparent = transparent
        self.walkable = walkable

class VicinityType(Enum):
    DIRT = VicinityID(ord("."), "#000000", "floor", True, True)
    STONE_WALL = VicinityID(ord("#"), "#000000", "wall", False, False)
    EVERGREEN_TREE = VicinityID(CP437_CHAR_SPADE, "#000000", "tree", False, True)
    TREE = VicinityID(CP437_CHAR_CLUB, "#000000", "tree", False, True)
    WATER = VicinityID(CP437_CHAR_EQUIVALENT, "#000000", "water", True, True)
    CONCRETE_WALL_HORIZONTAL = VicinityID(CP437_CHAR_DHLINE, "#000000", "wall", False, False)
    CONCRETE_WALL_VERTICAL = VicinityID(CP437_CHAR_DVLINE, "#000000", "wall", False, False)
    CONCRETE_WALL_NE = VicinityID(CP437_CHAR_DNE, "#000000", "wall", False, False)
    CONCRETE_WALL_NW = VicinityID(CP437_CHAR_DNW, "#000000", "wall", False, False)
    CONCRETE_WALL_SE = VicinityID(CP437_CHAR_DSE, "#000000", "wall", False, False)
    CONCRETE_WALL_SW = VicinityID(CP437_CHAR_DSW, "#000000", "wall", False, False)
    CONCRETE_WALL_TEEE = VicinityID(CP437_CHAR_DTEEE, "#000000", "wall", False, False)
    CONCRETE_WALL_TEEN = VicinityID(CP437_CHAR_DTEEN, "#000000", "wall", False, False)
    CONCRETE_WALL_TEEW = VicinityID(CP437_CHAR_DTEEW, "#000000", "wall", False, False)
    CONCRETE_WALL_TEES = VicinityID(CP437_CHAR_DTEES, "#000000", "wall", False, False)

    TARP_HORIZONTAL = VicinityID(CP437_CHAR_DHLINE, "#2E8B57", "tarp", False, True)
    TARP_VERTICAL = VicinityID(CP437_CHAR_DVLINE, "#2E8B57", "tarp", False, True)
    TARP_NE = VicinityID(CP437_CHAR_DNE, "#2E8B57", "tarp", False, True)
    TARP_NW = VicinityID(CP437_CHAR_DNW, "#2E8B57", "tarp", False, True)
    TARP_SE = VicinityID(CP437_CHAR_DSE, "#2E8B57", "tarp", False, True)
    TARP_SW = VicinityID(CP437_CHAR_DSW, "#2E8B57", "tarp", False, True)
    TARP_TEEE = VicinityID(CP437_CHAR_DTEEE, "#2E8B57", "tarp", False, True)
    TARP_TEEN = VicinityID(CP437_CHAR_DTEEN, "#2E8B57", "tarp", False, True)
    TARP_TEEW = VicinityID(CP437_CHAR_DTEEW, "#2E8B57", "tarp", False, True)
    TARP_TEES = VicinityID(CP437_CHAR_DTEES, "#2E8B57", "tarp", False, True)


    WOOD_FLOOR = VicinityID(ord("."), "#D2691E", "floor", True, True)
    WOOD_DOOR_CLOSED = VicinityID(ord("+"), "#D2691E", "door", False, False)
    WOOD_DOOR_OPEN = VicinityID(ord("-"), "#D2691E", "door", True, True)
    WOOD_BOARDED_WINDOW_HORIZONTAL = VicinityID(ord("="), "#D2691E", "window", False, False)
    WOOD_BOARDED_WINDOW_VERTICAL = VicinityID(ord("|"), "#D2691E", "window", False, False)
    WOOD_WALL_HORIZONTAL = VicinityID(CP437_CHAR_DHLINE, "#A0522D", "wall", False, False)
    WOOD_WALL_VERTICAL = VicinityID(CP437_CHAR_DVLINE, "#A0522D", "wall", False, False)
    WOOD_WALL_NE = VicinityID(CP437_CHAR_DNE, "#A0522D", "wall", False, False)
    WOOD_WALL_NW = VicinityID(CP437_CHAR_DNW, "#A0522D", "wall", False, False)
    WOOD_WALL_SE = VicinityID(CP437_CHAR_DSE, "#A0522D", "wall", False, False)
    WOOD_WALL_SW = VicinityID(CP437_CHAR_DSW, "#A0522D", "wall", False, False)
    WOOD_WALL_TEEE = VicinityID(CP437_CHAR_DTEEE, "#A0522D", "wall", False, False)
    WOOD_WALL_TEEN = VicinityID(CP437_CHAR_DTEEN, "#A0522D", "wall", False, False)
    WOOD_WALL_TEEW = VicinityID(CP437_CHAR_DTEEW, "#A0522D", "wall", False, False)
    WOOD_WALL_TEES = VicinityID(CP437_CHAR_DTEES, "#A0522D", "wall", False, False)

class VicinityColor(Enum):
    DIRT = (Palette.CORNSILK, Palette.BLACK, 0)
    STONE_WALL = (Palette.SLATEGRAY, Palette.DIMGRAY, auto())
    EVERGREEN_TREE = (Palette.DARKGREEN, Palette.BLACK, auto())
    TREE = (Palette.FORESTGREEN, Palette.BLACK, auto())
    WATER = (Palette.DEEPSKYBLUE, Palette.LIGHTSKYBLUE, auto())
    CONCRETE_WALL_HORIZONTAL = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_VERTICAL = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_NE = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_NW = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_SE = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_SW = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_TEEE = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_TEEN = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_TEEW = (Palette.SLATEGRAY, Palette.BLACK, auto())
    CONCRETE_WALL_TEES = (Palette.SLATEGRAY, Palette.BLACK, auto())
    TARP_HORIZONTAL = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_VERTICAL = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_NE = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_NW = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_SE = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_SW = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_TEEE = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_TEEN = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_TEEW = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    TARP_TEES = (Palette.MEDIUMSEAGREEN, Palette.BLACK, auto())
    WOOD_FLOOR = (Palette.CHOCOLATE, Palette.BLACK, auto())
    WOOD_DOOR_CLOSED = (Palette.CHOCOLATE, Palette.BLACK, auto())
    WOOR_DOOR_OPEN = (Palette.CHOCOLATE, Palette.BLACK, auto())
    WOOD_BOARDED_WINDOW_HORIZONTAL = (Palette.CHOCOLATE, Palette.BLACK, auto())
    WOOD_BOARDED_WINDOW_VERTICAL = (Palette.CHOCOLATE, Palette.BLACK, auto())
    WOOD_WALL_HORIZONTAL = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_VERTICAL = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_NE = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_NW = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_SE = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_SW = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_TEEE = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_TEEN = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_TEEW = (Palette.SIENNA, Palette.BLACK, auto())
    WOOD_WALL_TEES = (Palette.SIENNA, Palette.BLACK, auto())